### PR TITLE
pendaftaran ariqzuhdi

### PR DESCRIPTION
**Pull request by ariqzuhdi**
ariqzuhdi:

- [x] Tugas 1
- [x] Tugas 2
- [x] Tugas 3
- [ ] Tugas 4

### CODE REVIEW

**Comment by jayvdb** [comment]
Hi ariqzuhdi , please either
1. solve a problem, so you appear on https://projecteuler.net/country=Indonesia;page=2 or 
2. add me to your Project Euler friends list (friend key `943689_HYItqSjYuUBzlzh3h4ZW06wW8zX4uOJS`), so that I may check your username

cc: @nleni1976

**Comment by jayvdb** [comment]
Ok.  Now you need to redo the pull request, because it can not merge.

Github has a note here "This branch has conflicts that must be resolved".

Try to fix this PR first, using the github help.
If you are having trouble doing this, you can close this PR, and submit a new one.

**Comment by tadityar** [comment]
Another alternative is you can rebase it to the latest master branch.

**Comment by jayvdb** [comment]
48 hours remaining to submit a new Pull Request , or be disqualified.

**Pull request closed without merging**
