### PR TITLE
Update peserta-universitas.md

### PR DESCRIPTION
**Pull request by imintrovert**

### CODE REVIEW

**Comment by jayvdb** [comment]
:cop: Disqualified.

**Comment by imintrovert** [comment]
Why i'm disqualified sir? Please give me a reason

Jumat, 21 Oktober 2016, Suhendra Rahmat <sradisurya@gmail.com> menulis:

**Comment by imintrovert** [comment]
Why i'm disqualified sir? Please give me a reason.

2016-10-21 11:06 GMT+07:00 Suhendra Rahmat <sradisurya@gmail.com>:

**Comment by imintrovert** [comment]
Why , i'm disqualified

2016-10-21 10:59 GMT+07:00 John Vandenberg <notifications@github.com>:

**Pull request closed without merging**
