### PR TITLE
Update peserta-universitas.md

### PR DESCRIPTION
**Pull request by taufiqsumadi**
peserta

### CODE REVIEW

**Comment by laymonage** [comment]
Incomplete.

Checklist:

:heavy_check_mark: Registration form
:heavy_check_mark: Project Euler Baby Steps
:heavy_check_mark: GitHub Pages with Project Euler username
:x: 50 :star: GitHub repository contribution
:heavy_check_mark: bahasa Indonesia Wikipedia user page
:x: bahasa Indonesia Wikipedia content edit
:heavy_check_mark: StackOverflow account with at least one badge
:x: Besut Kode markdown Pull Request

1. You haven't contributed to the 50 ⭐️ repo (https://github.com/unila/unila.github.io/).
2. You haven't edited Wikipedia Indonesia content.
3. Your markdown edit isn't correct (see https://github.com/BesutKode/BesutKode.github.io/pull/158/files?short_path=4d5704e#diff-4d5704e09728aec131774db2621ee63b). Please edit it to follow the correct format.

Please submit a new pull request once more, after re-reading http://wikimedia-id.github.io/besutkode/university-modules-id.html and completing the tasks.

If you need help, ask on the Telegram chat group "[Besut Kode Universitas](https://telegram.me/joinchat/D9IRcQqFMoIiieZe5YYb_w)".

**Comment by taufiqsumadi** [comment]
Apakah untuk mendaftar sebagai peserta hanya di berikan kesempatan 2 kali
dalam mengajukan pull request di guthub. Peserta-universitas.md
Pada 16 Okt 2016 17.32, "Sage M.A." <notifications@github.com> menulis:

**Comment by jayvdb** [comment]
Ya. Hanya dua kali. Kamu butuh satu lagi.

**Comment by mzaini30** [comment]
@taufiqsumadi yang besut kode markdown pull request copas aja sama yang sebelumnya sambil diubah dikit tentang akun-akunmu

**Comment by taufiqsumadi** [comment]
@mzaini30 nah bagus idenya, gak kepikiran

**Pull request closed without merging**
