### PR TITLE
Update peserta-universitas.md

### PR DESCRIPTION
**Pull request by AryyNewbie**

### CODE REVIEW

**Comment by RioSatria** [comment]
Anda belum melakukan pull request di:
https://github.com/LibreOffice/core

**Comment by Aryy403** [comment]
Saya sudah melakukan Pull Request tadi pak.

**Comment by AryyNewbie** [comment]
Maaf pak saya telat melakukan Pull Request ke https://github.com/LibreOffice/core

**Comment by AryyNewbie** [comment]
langkah saya memperbaiki nya bagaimana pak?

**Comment by jayvdb** [comment]
> langkah saya memperbaiki nya bagaimana pak?

Technical assistance is provided by peers and mentors on Telegram, or you can ask questions on StackOverflow.
This Pull Request is being marked "pending", and will be accepted if completed properly on 21 October.

**Pull request merged**
