### PR TITLE
Update peserta.md

### PR DESCRIPTION
**Pull request by panggihsamudra**

### CODE REVIEW

**Comment by jayvdb** [comment]
https://panggihsamudra.github.io/ = HTTP 404

**Comment by panggihsamudra** [comment]
Done
Pada tanggal 15 Jul 2016 18.08, "John Vandenberg" <notifications@github.com>
menulis:

**Comment by panggihsamudra** [comment]
please check https://panggihsamudra.github.io/panggihsamudra/

**Comment by jayvdb** [comment]
That site is automatically generated.  Please customise/alter it a little.

**Comment by panggihsamudra** [comment]
done customise :)

**Comment by jayvdb** [comment]
OK. Ready to go except ...

Another participant has been added after you started this pull request, so now Github says "This branch has conflicts that must be resolved".

You can fix this by doing a `git rebase` on this patch, or by closing the pull request and starting a new one.

**Pull request closed without merging**
