### PR TITLE
Update peserta-universitas.md

### PR DESCRIPTION
**Pull request by ikhsanuddin**

### CODE REVIEW

**Comment by jayvdb** [comment]
:collision: Merge conflict ...

Checklist:

:heavy_check_mark: Formulir registrasi
:heavy_check_mark: Project Euler Baby Steps
:heavy_check_mark: GitHub Pages yang mencantumkan username Project Euler
:heavy_check_mark: kontribusi ke repositori GitHub yang memiliki 50 :star:
:heavy_check_mark: Halaman pengguna Wikipedia Indonesia 
:heavy_check_mark: Edit konten Wikipedia Indonesia
:heavy_check_mark: Akun StackOverflow dengan setidaknya satu badge
:heavy_check_mark: Pull Request Besut Kode dalam format Markdown

The only problem with your pull request is that it has a merge conflict.  As this is your second pull request, you must rebase and force push this PR.

Jika Anda butuh bantuan, silakan tanyakan di grup obrolan "[Besut Kode Universitas](https://telegram.me/joinchat/D9IRcQqFMoIiieZe5YYb_w)".

**Comment by jayvdb** [comment]
:boom: Merge conflict still.

:+1: You have force pushed to the pull request correctly.

:+1: You can continue practising here all day.  Ping me when [this](https://github.com/BesutKode/BesutKode.github.io/pull/237/files) looks good.

There are tutorials at https://github.com/endymuhardin/belajarGit and https://github.com/endymuhardin/buku-git , and you can ask for help on Telegram.

**Comment by ikhsanuddin** [comment]
I accidently deleted the forked repo

**Comment by jayvdb** [comment]
It was possible to resume this Pull Request with a new copy of the git repository.  But it is not possible for us to break the rules.

:no_entry_sign: :cop: Hanya dua Pull Request yang diperbolehkan sesuai ketentuan http://wikimedia-id.github.io/besutkode/university-modules-id.html .

Mohon untuk tidak mengirimkan Pull Request lagi untuk mengikuti Besut Kode Universitas.

**Comment by ikhsanuddin** [comment]
for the last post. i accidently pull a new request. i think it wild solve the problem

**Comment by jayvdb** [comment]
I agree that if done incorrectly, a new pull request can be created unintentionally and unexpectedly.
I really appreciate your attempt.  It is very good to see.

**Pull request closed without merging**
