### PR TITLE
update peserta

### PR DESCRIPTION
**Pull request by waderjhonson**
Hallo Besut Kode, saya melakukan perubahan pada peserta.md dengan rincian :

- Add Peserta baru , dengan nama Wader Trisepa Jonson

### CODE REVIEW

**Comment by jayvdb** [comment]
http://waderjhnson.github.io = HTTP 404

**Comment by waderjhonson** [comment]
ups, it's the right one :smile: [https://waderjhonson.github.io/](https://waderjhonson.github.io/)

**Comment by waderjhonson** [comment]
I already did commit repeated by changing the URL of my github , @jayvdb :smile:

**Comment by jayvdb** [comment]
Please either
1. Solve a problem, so you appear on https://projecteuler.net/country=Indonesia;page=2 or 
2. add me to your Project Euler friends list (friend key 943689_HYItqSjYuUBzlzh3h4ZW06wW8zX4uOJS), so that I may check your username

cc: @nleni1976

**Comment by waderjhonson** [comment]
okay, on my way ^^

**Comment by jayvdb** [comment]
Ping. Adding my friend key only takes a minute...

**Comment by jayvdb** [comment]
Resubmitted as #23

**Pull request closed without merging**
