### PR TITLE
Update peserta.md

### PR DESCRIPTION
**Pull request by rayanbg**

### CODE REVIEW

**Comment by jayvdb** [comment]
Your website https://rayanbg.github.io , and its code at https://github.com/rayanbg/rayanbg.github.io , is still 100% automatically generated.  You need to edit the code.

For example, see participant @reallyly's website at https://reallyly.github.io/ , and its code at https://github.com/reallyly/reallyly.github.io .

More examples at https://github.com/BesutKode/BesutKode.github.io/blob/master/peserta.md .

**Comment by rayanbg** [comment]
Oh ya, i forgot about that. I got many tasks from my school, so i can't
open my github via desktop. I will edit my site, soon.

**Comment by nutella25** [comment]
@rayanbg just for reminder, besutkode registration will be closed 20th september.

**Comment by jayvdb** [comment]
registration period ended 20 September 2016

**Pull request closed without merging**
