### PR TITLE
Update peserta-universitas.md

### PR DESCRIPTION
**Pull request by bagusarifudin**

### CODE REVIEW

**Comment by Arsfiqball** [comment]
Waduh....
Caritanya lagi rebutan nih yah 😂

**Comment by jayvdb** [comment]
:no_entry_sign: :anguished: Pull request kedua masih tidak lengkap = Tidak memenuhi syarat untuk mengikuti Besut Kode Universitas.

Pull request pertama: https://github.com/BesutKode/BesutKode.github.io/pull/224

Checklist untuk Pull Request kedua:

:heavy_check_mark: Formulir registrasi
:heavy_check_mark: Project Euler Baby Steps
:x: GitHub Pages yang mencantumkan username Project Euler
:heavy_check_mark: kontribusi ke repositori GitHub yang memiliki 50 :star:
:x: Halaman pengguna Wikipedia Indonesia 
:heavy_check_mark: Edit konten Wikipedia Indonesia
:heavy_check_mark: Akun StackOverflow dengan setidaknya satu badge
:heavy_check_mark: Pull Request Besut Kode dalam format Markdown (maksimum: 2)

Hanya dua Pull Request yang diperbolehkan sesuai ketentuan http://wikimedia-id.github.io/besutkode/university-modules-id.html.
Mohon untuk tidak mengirimkan Pull Request lagi untuk mengikuti Besut Kode Universitas.

**Comment by bagusarifudin** [comment]
Sorry. But I made a mistake and sent pulsss twice at the same time. I have
connection problems. I do not know if the first one is sent. Please, can I
get a chance again, I have been fixing the wrong

On Thursday, October 20, 2016, John Vandenberg <notifications@github.com>
wrote:
> Closed #226.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/fvVy6Fd63RpH5v50U56GCXEvkjFOEqOBJ20LtfMdfNCXWWsfpMwhhIBytkc4RKnSOT6FK5BNU2TuDBkzoRailK-jHSidl26cztcjWq4Cyy9VODIlC8QDI99g7tYlRa4da6ttvu5zLqbxMRlWvJQBkh62Bv3mFQ=s0-d-e1-ft#https://github.com/notifications/beacon/AVdIN4dE0DHh3jph51pjjJpIY_3VvZZVks5q1mRvgaJpZM4KbOGo.gif>

**Comment by bagusarifudin** [comment]
Sorry. But I made a mistake and sent pulsss twice at the same time. I have connection problems. I do not know if the first one is sent. Please, can I get a chance again, I have been fixing the wrong

**Comment by jayvdb** [comment]
It is possible to check whether you have already submitted a request.  Everything you do is public, appearing on your GitHub profile, with timestamps: https://github.com/bagusarifudin

**Pull request closed without merging**
