### PR TITLE
fixed PR for #104

### PR DESCRIPTION
**Pull request by reksasuhud97**
fixed PR for #104

### CODE REVIEW

**Comment by jayvdb** [comment]
sorry. Merge conflict.

**Comment by reksasuhud97** [comment]
I'm sorry. Then, how i can fix this?

**Comment by jayvdb** [comment]
Start a new Pull Request is the easy solution. For the proper solution, search online, esp. stackoverflow.

**Comment by reksasuhud97** [comment]
okay, i created the new one. can you please check #108?

**Comment by laymonage** [comment]
Merged.

**Pull request closed without merging**
