### PR TITLE
Update peserta.md

### PR DESCRIPTION
**Pull request by Kazemani118**

### CODE REVIEW

**Comment by jayvdb** [comment]
Hi @Kazemani118 , have you put your answers into Project Euler. I do not see your username on https://projecteuler.net/country=Indonesia;page=2

**Comment by Kazemani118** [comment]
done 3 numbers https://projecteuler.net/country=Indonesia;page=2 iqbalbintang

**Comment by jayvdb** [comment]
Ok. Due to delay, peserta.md has other changes.

https://github.com/BesutKode/BesutKode.github.io/commits/master

You can try `git rebase` or start a new pull request.

https://github.com/BesutKode/BesutKode.github.io/edit/master/peserta.md

**Comment by jayvdb** [comment]
Please submit a new pull reques.t

**Pull request closed without merging**
