### PR TITLE
riyan010699

### PR DESCRIPTION
**Pull request by riyan010699**
[Modul 2](http://wikimedia-id.github.io/besutkode/modul.html#modul2):

- [x] Tugas 1
- [x] Tugas 2
- [x] Tugas 3
- [ ] Tugas 4

Tenggat tugas: 20 September 2016

### CODE REVIEW

**Comment by jayvdb** [comment]
@riyan010699 , this pull request is a "merge conflict".
Easiest solution is to start editing the file again. See my link above.

**Comment by jayvdb** [comment]
Completed in #80

**Comment by riyan010699** [comment]
when i could access solusi repo?

**Comment by jayvdb** [comment]
You have been sent an invitation via email.
If you didnt receive it, you can also go to https://github.com/BesutKode to accept the invitation.

**Pull request closed without merging**
