### PR TITLE
updating my data.

### PR DESCRIPTION
**Pull request by reallyly**
I've finished "Tugas 2". What should I do now @jayvdb ?

### CODE REVIEW

**Comment by jayvdb** [comment]
Keep adding your code to https://github.com/BesutKode/solusi/tree/master/reallyly for modul 3, and start working on problem 169 for modul 4.

**Comment by reallyly** [comment]
@jayvdb  So, should I upload all of my codes..? I solved at least one Project Euler problem with pencil..
And, should I work on problem 169 myself or teamed up with other(s)?

**Comment by jayvdb** [comment]
Yea, upload all your code to the repository. I use it to check that you actually understand the problem & dolusion.

**Comment by jayvdb** [comment]
And see the `README.md` in the solusi repository , to join the Besut Kode group chat.

**Comment by reallyly** [comment]
Okay. But how about the problems which I don't have the solution code? Like, the one I did with pencil+paper? Also I don't have telegram nor Line, and I've joined the discord.

**Comment by jayvdb** [comment]
We will continue the discussion on Discord.

**Pull request merged**
