### PR TITLE
Update peserta.md

### PR DESCRIPTION
**Pull request by rayanbg**
[Modul 2](http://wikimedia-id.github.io/besutkode/modul.html#modul2):

- [x] Tugas 1
- [x] Tugas 2
- [ ] Tugas 3
- [x] Tugas 4

Tenggat tugas: 20 September 2016

### CODE REVIEW

**Comment by jayvdb** [comment]
I see that you created a `README.md` in your Github Pages website.
Please also edit your Github Pages website, as it is currently only automatically generated files.
It doesnt need to be a big edit - even just delete some of the irrelevant content.
Thank you!
Add a comment here when you have done that.

**Comment by rayanbg** [comment]
Yes sir, i make that README.md in my github page website. I will edit
github pages website, soon. Because my school gave too many homeworks. And
my hand just injured last week. I just wanna back to programming activity,
but i don't know how to start it. I hope you can help me , Sir. Sorry for
the late reply.

Regards,
Rayandra

**Comment by jayvdb** [comment]
Please ping me here with "@jayvdb" when you have customised https://rayanbg.github.io/ .

**Comment by rayanbg** [comment]
how to customised it? @jayvdb

**Comment by jayvdb** [comment]
Look at the github profile of the other people already in peserta.md?  Copy what they did?

**Comment by rayanbg** [comment]
Done :) @jayvdb

**Comment by jayvdb** [comment]
New pull request at #71

**Pull request closed without merging**
